<a href="https://colab.research.google.com/github/suminkkk/DA_STUDY/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%20%ED%95%B8%EB%93%A4%EB%A7%81/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Numpy

- 파이썬 라이브러리 중 하나 -> 과학 연산
- 배열  -> 행렬 (선형대수)
- 선형대수, 푸리에 변환 -> 수학 함수 사용 가능 


In [ ]:
import numpy as np

In [ ]:
#1차원 배열 생성

a = np.array([1,2,3,4]) 
print(a)

[1 2 3 4]


In [ ]:
#list 
l = [1,2,3,4]
print(l)

[1, 2, 3, 4]


In [ ]:
# 배열 축의 크기
print(a.shape)

(4,)


In [ ]:
# 배열 차원(dimension)
print(a.ndim)

1


In [ ]:
# data type
print(a.dtype)

int64


In [ ]:
# byte단위 크기 
print(a.itemsize)

8


In [ ]:
# 2차원 배열 생성
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
print(b)
print(b.ndim)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

[[1 2]
 [3 4]]
2
int64
8
32


In [ ]:
# 3차원 배열 생성
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
int64
8
64


In [ ]:
# 하나의 숫자값 : 스칼라

s = np.array(1)
print(s)

1


In [ ]:
#1차원 : 벡터

v = np.array([1,2,3])
print(v)

[1 2 3]


In [ ]:
#2차원 : 행렬(Matric)

m =  np.array([[1,2,3],[1,2,3]])
print(m)

[[1 2 3]
 [1 2 3]]


In [ ]:
#3차원 : 텐서(Tensor)

t = np.array([[[1,2],[1,2]],[[1,2],[1,2]]])
print(t)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [ ]:
# for문을 이용해서 배열 생성

f = np.array([i for i in range(0,10,2)])    #(start,end,step)
print(f)

[0 2 4 6 8]


In [ ]:
print(f)
print(f.ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

[0 2 4 6 8]
1
int64
8
40


# 데이터 타입
1. 숫자형
2. 문자형
3. 논리형

## 숫자형
- 부호가 있는 정수(Signed integer) int
- 부호가 없는 정수(Unsigned integer) uint
- 실수(floating point) float
- 복소수(complex) complex

In [ ]:
# int (8bit, 16bit, 32bit, 64bit)

data = [1.1, 2, 3]
i = np.array(data, dtype = np.int32)
print(i)

[1 2 3]


In [ ]:
print(i.dtype)

int32


In [ ]:
# 데이터 타입의 범위 

data2 = [-1,2,3]

ui = np.array(data2, dtype=np.uint32)
print(ui)

[4294967295          2          3]


In [ ]:
# int -> float

f = np.array(data, dtype = np.float64)
print(f)

[1.1 2.  3. ]


In [ ]:
c = np.array([1 + 2j, 3+4j, 5 + 6j], dtype=np.complex64)
print(c)
print(c.real)   #실수
print(c.imag)   #허수

[1.+2.j 3.+4.j 5.+6.j]
[1. 3. 5.]
[2. 4. 6.]


## 문자형

- string_
- unicod_

In [ ]:
data = [1,2,3]

s = np.string_(data)
print(s)

b'\x01\x02\x03'


In [ ]:
#S3 : string 3개

print(s.dtype)

|S3


In [ ]:
data3 = [1,2,3,4,5]

#string_
s2 = np.string_(data3)

print(s)
print(s.dtype)

b'\x01\x02\x03'
|S3


In [ ]:
# np.string_ 과 동일 
s2 = np.array(data3, dtype = 'S')
print(s2)

[b'1' b'2' b'3' b'4' b'5']


In [ ]:
#unicode - 사용자에게 보여줄때. 용량이 큼
u = np.array(data3, dtype='U')
print(u)
print(u.dtype)

['1' '2' '3' '4' '5']
<U1


In [ ]:
data4 = [11,22,33,44,55]
u2 = np.array(data4, dtype='U')
print(u2)
print(u2.dtype)

['11' '22' '33' '44' '55']
<U2


## 논리형(boolean)
- True(1), Fals(0)
- 비트 연산사용 : &and, |or, ^xor, ~not

In [ ]:
l1 = np.array([True,False,True])
l2 = np.array([False,True, False])

print(l1)
print(l2)

[ True False  True]
[False  True False]


In [ ]:
and_ = np.logical_and(l1,l2)
print(and_)

[False False False]


## 데이터 형 변환 (Cast, Casting 형 변환)

- 데이터들끼리 형태를 맞춰줌
- 예시) 이미지 데이터 -> uint 형으로 불러옴 -> float(정제,처리)

In [ ]:
# float
data = [1.1,2,3]

a = np.float64(data)
print(a)
print(a.dtype)

[1.1 2.  3. ]
float64


In [ ]:
# astype
a = a.astype(np.int64)
print(a.dtype)

int64


In [ ]:
# uint
b = np.uint16(0)

print(b)
print(b.dtype)

0
uint16


In [ ]:
b = b-1
print(b)

-1


In [ ]:
# uint(0 ~ 65,535)
c = np.uint16(-1)
print(c)

65535


# 산술연산

In [ ]:
import time

data = [[1,2,3],[4,5,6]]
data2 = [[1,1,1],[2,2,2]]

strat_time = time.time()

sum = 0
for i in range(len(data)):
    for j in range(len(data[0])):
        print(data[i][j])
        sum += data[i][j]
        
print(sum)

1
2
3
4
5
6
21


In [ ]:
# numpy 배열끼리의 연산
a = np.array([1,2,3])
b = np.array([4,5,6])

# 덧셈
sum = a + b 

# 뺄셈
min = a - b

#곱셈
mul = a * b

#나눗셈
div = a / b

print(sum)
print(min)
print(mul)
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# 지수함수
a = np.array([1,2,3])
b = np.array([4,5,6])

aa = np.exp(a)
print(aa)

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
# 자연로그
bb = np.log(b)
print(bb)

[1.38629436 1.60943791 1.79175947]


In [ ]:
# 밑이 2인 로그
cc = np.log2 
print(cc)

<ufunc 'log2'>


In [ ]:
# 삼각함수

d = np.array([0, np.pi/2, np.pi])

sin_ = np.sin(d)
cos_ = np.cos(d)
tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


# 배열의 연결과 분할

In [ ]:
print("a"+"b")

ab


In [ ]:
x = [1,2,3]
y = [4,5,6]

concat = np.concatenate([x,y])
print(concat)

[1 2 3 4 5 6]


In [ ]:
x2 = [[1,2],[3,4]]
y2 = [[4,5],[6,7]]

concat2 = np.concatenate([x2,y2], axis=1)   #열 병합
concat3 = np.concatenate([x2,y2], axis=0)   #행 병합 
print(concat2)
print(concat3)

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
print(x2)

[[1, 2], [3, 4]]


In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr.reshape(2,5)        #행2개 열5개 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#hstack (horizontal) - 수평 (열방향)

h = np.hstack([x2,y2])
print(h)

[[1 2 4 5]
 [3 4 6 7]]


In [ ]:
#vstack (vertical) - 수직(행방향)

v = np.vstack([x2,y2])
print(v)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
# hsplit

x2 = np.array([[1,2],[3,4],[5,6]])
h2 = np.hsplit(x2, 2)
print(h2)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [ ]:
# vsplit

v2 = np.vsplit(x2,3)
print(v2)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


# 다양한 배열 만들기

In [ ]:
# 0행렬

zero = np.zeros([3,4])
print(zero)


zero3  = np.zeros([3,4,2])
print(zero3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
one = np.ones([3,4])
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy 제공 함수

## 범용함수

In [ ]:
# abs 절대값

arr1 = np.array([-1,-2,-3,-4])
abs_arr = np.abs(arr1)
print(abs_arr)

[1 2 3 4]


In [ ]:
# sqrt 제곱근
arr2 = np.array([1,4,9,16])
sqrt_arr = np.sqrt(arr2)

print(sqrt_arr)

[1. 2. 3. 4.]


## 집계함수

In [ ]:
# 평균 mean
a = np.array ([1,2,3,4,5])
a_mean = np.mean(a)

print(a_mean)

3.0


In [ ]:
# 중앙값 median
b = np.array([1,3,5,7,9])
b_median = np.median(b)
print(b_median)

5.0


In [ ]:
# 표준편차 std
c = np.array([1,2,3,4,5])
c_std = np.std(c)

print(c_std)

1.4142135623730951


In [ ]:
# 분산 var
d = np.array([1,2,3,4,5])
d_var = np.var(d)

print(d_var)

2.0


In [ ]:
# 합계 sum
d = np.array([1,2,3,4,5])
d_sum = np.sum(d)
print(d_sum)

15


In [ ]:
# 누적합계 cumsum

d_cumsum = np.cumsum(d)
print(d_cumsum)

[ 1  3  6 10 15]


In [ ]:
# min, max 최소최대 : 인덱스 반환 
min = np.argmin(d)
print(min)

0


In [ ]:
max = np.argmax(d)
print(max)

4


In [ ]:
# any - 배열 안에 하나라도 true가 있는지

a = np.array([0,0,0,1])

a_true = np.any(a)
print(a_true)

True


In [ ]:
# all - 모든게 true 여야 true

a_all = np.all(a)
print(a_all)

False


In [ ]:
# NaN

a = np.array([1,2,np.nan,4])
a_nsum = np.nansum(a)

print(a_nsum)

7.0


In [ ]:
# nan이 있을경우 sum 에러
a_sum = np.sum(a)
print(a_sum)

nan


In [ ]:
# 조건 where 

d = np.array([1,2,3,4,5])

condition = np.where( d < 3, d, 0)
condition1 = np.where(d < 3)
print(condition)
print(condition1)

[1 2 0 0 0]
(array([0, 1]),)


## Boolean Indexing

## 조건에 따른 요소들을 판별해 새로운 배열을 만든다.

In [ ]:
# 참이 되는 조건만 반환 

a = np.array([1,2,3,4,5,6,7,8,9,10])        #원본데이터

even_a = a[a%2 == 0 ]

print(even_a)
print(a)

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


## Broadcast(브로드캐스트)

- 크기가 다른 배열 간의 연산도 가능하게 해줌 
- ex) 1차원, 2차원
- 두 배열의 차원이 다르고 한 배열의 차원이 1차원(벡터)
- 차원을 늘렸을 때 계산 가능한 경우 

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a+b 
print(c)

[5 7 9]


In [ ]:
# 백터 - 행렬 (다른 차원의 계산)
d = np.array([[1],[2],[3]])
e = np.array([4,5,6])

f = d+e
print(f)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


- 두 배열의 차원 수가 다를 경우, 더 작은 차원의 배열에 큰차원의 배열이 맞을 때까지 1을 추가한다. 
- 두 배열의 차원 수가 같을 경우에도, 크기가 1인 차원이 있다면 다른 배열의 크기와 일치하도록 복제된다.  
- 두 배열의 차원 수가 같은 경우에도, 모든 차원의 크기가 같거나 크기가 1이라면 모양이 같은 두 배열의 요소 간 연산을 한다. 

In [ ]:
# 1x3
f = np.array([[1, 2, 3]])

## 난수 생성 함수
random

In [1]:
import numpy as np 

In [2]:
# rand : 0~1 사이 랜덤 값 

a = np.random.rand(2,2)
print(a)

[[0.43745247 0.1679137 ]
 [0.5474366  0.57558971]]


In [3]:
# randn(표준정규분포) : 평균이 0, 분산이 1 
b = np.random.randn(2, 2)
print(b)

[[ 1.38181426 -0.4519734 ]
 [-0.73803004  0.4506318 ]]


In [4]:
#randint : 랜덤한 정수값 

c =  np.random.randint(0,10,size = 5)
print(c)

[4 0 9 6 4]


In [7]:
c2 =  np.random.randint(0,10,size = (2,2))
print(c2)

[[0 6]
 [7 4]]


In [11]:
# shuffle - 값 섞기

d = np.arange(10)
np.random.shuffle(d)            #원본 값이 변함
print(d)

[8 4 7 3 1 2 9 6 0 5]


In [14]:
# choice - 중복허용
# choice + replace=False  - 중복허용x

choice = np.random.choice(d, 5)
choice2 = np.random.choice(d, 5, replace=False)

print(choice)
print(choice2)

[5 5 2 0 4]
[0 9 5 6 4]


In [24]:
# 지정확률로 뽑기
d=  np.arange(5)
choice = np.random.choice(d, 5, p=[0.1, 0, 0.3, 0.2, 0.4])
print(choice)

[4 3 3 4 3]


In [27]:
# permutation 순열 (원본 안바뀜)

a = np.arange(10)
a_p = np.random.permutation(a)
print(a)
print(a_p)

[0 1 2 3 4 5 6 7 8 9]
[1 7 2 3 4 5 0 9 8 6]


In [28]:
# 정규분포를 따르는 난수 생성 
# a = np.random.noraml('평균','표준편차','갯수')

a = np.random.normal(0,1,3)
print(a)

[-0.315598   -0.50605006  0.04142523]


# 복습예제

## array()

In [ ]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [ ]:
arr_1d = np.array([i for i in range(1,10,2)])
print(arr_1d)

[1 3 5 7 9]


In [ ]:
print(np.array(range(10)))
print(np.array(range(1,11)))
print(np.array(range(2,11,2)))
print(np.array(range(10,2,-1)))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[10  9  8  7  6  5  4  3]


In [ ]:
arr_1d = np.array([1,2,3,4,5],dtype="f")
print(arr_1d)

[1. 2. 3. 4. 5.]


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [121]:
arr_2d = np.array(range(1,13,2)).reshape(2,3)
print(arr_2d)

[[ 1  3  5]
 [ 7  9 11]]


In [122]:
# 요소 개수 reshape 의 행렬 개수에 맞게 설정
arr_2d = np.array(range(1,13,2)).reshape(2,4)
print(arr_2d)


ValueError: ignored

In [123]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 2. arange()

In [124]:
print(np.array(range(10)))
print(np.array(range(1, 11)))
print(np.array(range(2, 11, 2)))
print(np.array(range(2, 11, 0.5)))
print(np.array(range(10, 2, -1)))
print(np.array(range(10, 2, -0.5)))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


TypeError: ignored

In [125]:
print(np.arange(10))
print(np.arange(1, 11))
print(np.arange(2, 11, 2))
print(np.arange(2, 11, .5))
print(np.arange(10, 2, -1))
print(np.arange(10, 2, -.5))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10.  10.5]
[10  9  8  7  6  5  4  3]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5]


## 3. 다양한 배열 

In [126]:
# ravel : 일차원으로 변경 

arr_3d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [136]:
# zeros : 0으로 채워진 배열

a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [134]:
# ones : 1로 채워진 배열 생성

a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [138]:
# full : 내가 원하는 값으로 채워진 배열 

a = np.full((2,2),10)
a

array([[10, 10],
       [10, 10]])

In [139]:
# 단위행렬

a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 연습문제

In [ ]:
# 1. 1차원 배열 연결해 하나의 큰 1차원 배열로 반환

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])

newarr= np.concatenate([arr1,arr2,arr3])
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#2. 2차원 배열에서 각 열의 평균 계산해 1차원 배열로 

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

np.mean(arr,axis=0)

array([4., 5., 6.])

In [ ]:
#3. 2차원 배열에서 각 행의 최대값 구해 1차원 배열 반환

np.max(arr, axis =1)

array([3, 6, 9])

In [120]:
#4. 0에서 1사이의 값으로 크기10 1차원 배열

np.linspace(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
#5. 1차원 배열 짝수 요소 합 계산 

def sum_of_evens(arr:np.ndarray) -> int :
    evens = arr[arr%2 ==0]
    return np.sum(evens)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(sum_of_evens(arr))

30


In [ ]:
#6. 수평분할, 수직분할, 수평스택, 수직 스택 

arr = np.arange(1, 13).reshape((3, 4))
print("==============원본 배열:")
print(arr)

==============원본 배열:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:

#수평분할
print("==============수평분할")
arr_split = np.hsplit(arr,2)
print(arr_split)
print("==============수평병합")
arr_1 = arr_split[0]
arr_2 = arr_split[1]
arr_stack = np.hstack((arr_1, arr_2))
print(arr_stack)


==============수평분할
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
==============수평병합
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#수직분할
print("==============수직분할")
arr_split = np.split(arr,3)
print(arr_split)

print("==============수직병합")
arr_1 = arr_split[0]
arr_2 = arr_split[1]
arr_3 = arr_split[2]
arr_stack = np.vstack((arr_1, arr_2, arr_3))
print(arr_stack)

==============수직분할
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
==============수직병합
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 7. 조건에 맞는 값 반환 10으로 나누었을때 나머지가 0이면 원래값, 아니면 0 출력

arr = np.arange(0, 100, 5).reshape((5,4))
print(arr)

print(np.where(arr%10==0, arr, 0))

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]
[[ 0  0 10  0]
 [20  0 30  0]
 [40  0 50  0]
 [60  0 70  0]
 [80  0 90  0]]


In [ ]:
# 8. 3x3 배열중 짝수만 뽑아내는 인덱싱 배열을 사용해 짝수 배열 생성

lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)
print(a)

n = a[ a % 2 == 0 ]
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 4 6 8]


In [ ]:
#  9
# 사인 함수 계산

angle = np.pi / 3 # 라디안 표기 = 60도 
# 360도는 2라디안 으로, 180도는 1라디안으로 표현합니다.

# 사인 
sin_value = np.sin(angle)
print("사인 값:", sin_value)

# 코사인 함수 계산
cos_value = np.cos(angle)
print("코사인 값:", cos_value)

# 탄젠트 함수 계산
tan_value = np.tan(angle)
print("탄젠트 값:", tan_value)

사인 값: 0.8660254037844386
코사인 값: 0.5000000000000001
탄젠트 값: 1.7320508075688767


In [ ]:
# 10 . 짝수 2배로
arr = np.array([1, 2, 3, 4, 5])

new_arr = np.where(arr % 2 == 0, arr * 2, arr)
print("조건을 만족하는 요소를 2배로:", new_arr)

조건을 만족하는 요소를 2배로: [1 4 3 8 5]


# 연습문제2

## 배열

In [2]:
#사이즈 10의 Null(0) 1차원 배열을 만들기

import numpy as np

zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
# 10~49인 1차원 배열

np.array(range(10,50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [3]:
# 0~8까지 3x3 배열

np.array([[[0,1,2],[3,4,5],[6,7,8]]])

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 5x5 경계값 1 

a = np.ones((5,5))
print(a)
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 랜덤함수

In [13]:
# 3x3x3  랜덤 

np.random.rand(3,3,3)

array([[[0.12898096, 0.20874788, 0.37789029],
        [0.17407295, 0.4356155 , 0.05861744],
        [0.82610389, 0.33936736, 0.77746211]],

       [[0.13558931, 0.49846655, 0.83831276],
        [0.50719556, 0.1054001 , 0.05239592],
        [0.66128927, 0.53355095, 0.48142358]],

       [[0.50315612, 0.71584431, 0.08149272],
        [0.23226235, 0.45536749, 0.38236529],
        [0.62464968, 0.59088054, 0.62502555]]])

In [15]:
# 10x10배열 최소 최대

a = np.random.rand(10,10)
amax = a.max()
amin = a.min()


print(a)
print(amax)
print(amin)

[[6.96001412e-01 8.24994257e-04 1.05220420e-01 3.91560102e-01
  5.99695772e-01 3.60589704e-01 1.70630568e-01 1.85986498e-01
  9.17316119e-01 1.54335509e-01]
 [6.44307957e-01 5.80968963e-01 9.52495121e-01 3.00531066e-01
  2.62115402e-01 9.61969954e-01 6.12529400e-01 2.85582783e-01
  1.35027895e-01 7.82111878e-01]
 [9.11606936e-01 3.58965329e-01 8.08735902e-01 2.64712957e-01
  2.70143821e-01 7.28807247e-01 6.88600160e-01 2.91858102e-01
  1.39480412e-01 1.69975129e-01]
 [6.35975121e-01 8.11085314e-01 7.39342675e-01 5.47877952e-01
  7.20882975e-01 4.73218712e-01 9.70369194e-01 5.62851469e-01
  8.61127913e-01 5.46759444e-01]
 [1.04087705e-01 5.91360379e-01 7.53653903e-01 9.11451134e-01
  7.24240418e-01 2.59139098e-01 5.32362970e-01 6.30117229e-01
  9.56406336e-01 2.99334706e-01]
 [1.56020698e-01 3.49088351e-01 4.38949100e-01 2.93648965e-01
  7.10449862e-01 2.06830550e-01 6.66597019e-01 2.40145917e-02
  4.31305808e-01 6.37953769e-01]
 [6.59160074e-01 9.53578452e-01 3.92648421e-01 5.30603944e

In [26]:
thirty = np.random.rand((30))
tmean = thirty.mean()
tmean

0.5229751042426071

## 행렬

In [30]:
x, y = np.ones((5,3)), np.ones((3,2))
z = np.dot(x,y)
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [33]:
# 연산을 제로행렬C에 갚 덮어씌우기
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.zeros(3)

np.add(A,B, out = C)
C

array([5., 7., 9.])

In [36]:
# A배열 부호 반전시켜 C에 

nega_c = np.negative(A, out=C)
nega_c

array([-1., -2., -3.])

In [44]:
# 크기 10 개 1차원 랜덤 행렬 최댓값 0

a = np.random.random(10)
print(a)
amax = a.argmax()
print(amax)
z[z.argmax()] = 0
z

[0.96722595 0.28697634 0.32154174 0.95024602 0.75374243 0.07675923
 0.40298147 0.99516743 0.37958374 0.34019395]
7


array([[0., 0.],
       [3., 3.],
       [0., 0.],
       [3., 3.],
       [3., 3.]])

In [53]:
# 각 열과 행별 최댓값 반환, 인덱스 호출

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.max())
print(arr.argmax())
print(arr.max(axis=0))
print(arr.max(axis=1))
print(np.argmax(arr,axis=0))
print(np.argmax(arr,axis=1))

6
5
[4 5 6]
[3 6]
[1 1 1]
[2 2]


## 형변환

In [75]:
# 균일분포 랜덤함수 0~100 1차원 실수(32비트)행렬 

a = (np.random.rand(10)*100).astype(np.float32)
a

array([27.715101 , 50.445538 , 50.91297  , 21.506483 , 61.8591   ,
       90.28884  , 19.861353 , 41.45941  , 34.760765 ,  4.6667566],
      dtype=float32)

In [77]:
# 정수이며 배열모양 10x1

b = a.view(np.int32)
b.shape = (10,1)
b

array([[1105049735],
       [1112131643],
       [1112254178],
       [1101794631],
       [1115123640],
       [1119130595],
       [1100932109],
       [1109775984],
       [1108019974],
       [1083528722]], dtype=int32)

In [81]:
# 집계함수로 null값 확인
# 정수형 난수로 3x10
# 0~5 까지 값

a = np.random.randint(0,6,size=(3,10))
print(a)

a.any()

[[1 3 0 4 2 1 0 2 4 3]
 [0 2 2 4 2 1 5 1 0 2]
 [1 3 3 4 3 5 2 4 0 5]]


True

## 정규분포, 균일분포

In [88]:
# 0~1 사이 10개 값 균일분포 배열 

a = np.random.uniform(0,1,10)
print(a)

#지정된 값에 가장 가까운 값 찾기 

num = 0.5
print(np.abs(a-num).argmin())
a[np.abs(a-num).argmin()]

[0.54218976 0.76553853 0.15698145 0.89661406 0.96251717 0.01402295
 0.84556671 0.58849606 0.90501133 0.94826091]
0


0.5421897570720324

In [99]:
# 다차원 배열을 1차원으로 평면화 flatten
# 3 차원 배열 -> 1차원 -> 최대값 10

arr = np.array([[1, 2, 3], [4, 5, 6], [3, 4, 5]])

flat_arr = arr.flat
print(arr.argmax())

flat_arr[arr.argmax()] = 10 

print(arr)

5
[[ 1  2  3]
 [ 4  5 10]
 [ 3  4  5]]


In [106]:
# 4차원(3,4,3,4) 범위(0,10) 정수형 변수 생성
# 마지막 2축에서 합계 출력

a = np.random.randint(0,10,size=(3,4,3,4))
a.sum(axis=(-2,-1))

array([[58, 77, 43, 69],
       [47, 48, 47, 75],
       [60, 45, 35, 53]])

In [111]:
# 배열의 첫번째행과 두번째행 바꾸기

A = np.arange(25).reshape(5,5)
print(A)

A[[0,1]] = A[[1,0]]
A

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## arg 인덱스 접근 함수 추가

In [113]:
# argmax,argmin응용
# 표준정규분포 100개 난수 생성. shuffle() 사용해 순서 섞기 . argsot() 인덱스 사용.


a = np.random.randn(100)
a

array([-1.03568446, -0.85718416,  1.06244245,  0.46602729, -0.15159945,
       -0.1314949 , -1.77337218, -0.57058581, -2.36993195,  2.00341773,
       -0.76792352, -2.43981901,  0.56199837,  1.07495788, -1.46423187,
        1.91719103,  0.39351839,  1.64016257,  0.80298638, -0.21126161,
       -1.05951076,  0.73324075, -0.51018942,  1.06735351,  1.34355911,
       -1.67754643,  0.67927614, -1.48049446, -0.38552962,  0.07898188,
        2.59464024, -1.27220766, -0.3458743 , -0.59881294,  0.26642073,
       -0.86581649,  1.33473305, -0.21852008,  0.89643991,  0.26503607,
        0.21599513,  1.29983601,  1.13841953, -0.5929205 , -0.3305276 ,
       -0.9381194 , -0.5915021 ,  0.92665111, -0.10307218,  0.51076862,
       -0.01531296,  0.49098486,  2.40140193,  0.22252821, -1.1614158 ,
       -1.21640561, -0.53783756, -0.78509045, -0.15248337,  1.20683465,
        0.25166449, -1.19237388,  0.17429816, -0.84307644,  0.47740005,
        1.28740132,  1.41224198, -0.02603163, -0.87597595,  0.27

In [116]:
np.random.shuffle(a)
a[np.argsort(a)[-5:]]

array([1.64016257, 1.91719103, 2.00341773, 2.40140193, 2.59464024])

In [119]:
arr = np.array([1,3,2,5,4])

max_index = np.argmax(arr)
min_index = np.argmin(arr)
index = np.argwhere(arr > 2)
selected_index = np.argmax(arr>2)
nonzero = np.nonzero(arr)

print("max:",max_index, "min:",min_index, "index:",index, "selected: ",selected_index, "nonzero:",nonzero)

max: 3 min: 0 index: [[1]
 [3]
 [4]] selected:  1 nonzero: (array([0, 1, 2, 3, 4]),)
